/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'

const LayoutAboutIndexLazyRouteImport = createFileRoute('/_layout/about/')()
const LayoutHomeIndexLazyRouteImport = createFileRoute('/_layout/_home/')()

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAboutIndexLazyRoute = LayoutAboutIndexLazyRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/about/index.lazy').then((d) => d.Route),
)
const LayoutHomeIndexLazyRoute = LayoutHomeIndexLazyRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/_home/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof LayoutHomeIndexLazyRoute
  '/about/': typeof LayoutAboutIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutHomeIndexLazyRoute
  '/about': typeof LayoutAboutIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_home/': typeof LayoutHomeIndexLazyRoute
  '/_layout/about/': typeof LayoutAboutIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about'
  id: '__root__' | '/_layout' | '/_layout/_home/' | '/_layout/about/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/about/': {
      id: '/_layout/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof LayoutAboutIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_home/': {
      id: '/_layout/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutHomeIndexLazyRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutHomeIndexLazyRoute: typeof LayoutHomeIndexLazyRoute
  LayoutAboutIndexLazyRoute: typeof LayoutAboutIndexLazyRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutHomeIndexLazyRoute: LayoutHomeIndexLazyRoute,
  LayoutAboutIndexLazyRoute: LayoutAboutIndexLazyRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
